version: "3.9"
services:
  voucher_db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voucher_pool

  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      POSTGRES_HOST: voucher_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voucher_pool
    depends_on:
      - voucher_db